# Generated by Django 2.2 on 2021-07-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0002_auto_20210707_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='scrapped_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Scrapped url'),
        ),
    ]
