# Generated by Django 2.2 on 2021-07-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0003_comunidad_scrapped_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='scrapped_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Scrapped url'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='scrapped_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Scrapped url'),
        ),
    ]
