# Generated by Django 2.2 on 2021-07-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provinces', '0004_auto_20210707_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='comunidad',
        ),
        migrations.AddField(
            model_name='municipio',
            name='provincia',
            field=models.ForeignKey(default=None, help_text='Provincia a la que pertenece', on_delete=django.db.models.deletion.PROTECT, to='provinces.Provincia', verbose_name='Provincia a la que pertenece'),
            preserve_default=False,
        ),
    ]
